config/routes.rb
Rails.application.routes.draw do

  root "high_voltage/pages#show", id: 'home'

  get  "/register", to: "registrations#new"
  post "/register", to: "registrations#create"

  post  "/login", to: "login#create"
  delete  "/logout", to: "login#destroy"

  # Normal App routes
  resources :jobs
  resources :users do
    resources :skills
  end

  resources :companies do
    resources :admins
  end

  # API Routes
  namespace :api do
    resources :users, only: [:index, :show]
    resources :jobs, only: [:index, :show]
    resources :companies, only: [:index, :show]
  end
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_area :password_digest %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Password digest</th>
      <th>Email</th>
      <th>Title</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.first %></td>
        <td><%= admin.last %></td>
        <td><%= admin.password_digest %></td>
        <td><%= admin.email %></td>
        <td><%= admin.title %></td>
        <td><%= admin.company_id %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @admin.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @admin.last %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @admin.password_digest %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @admin.title %>
</p>

<p>
  <strong>Company:</strong>
  <%= @admin.company_id %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>