config/routes.rb
Rails.application.routes.draw do

  root "high_voltage/pages#show", id: 'home'

  get  "/register", to: "registrations#new"
  post "/register", to: "registrations#create"

  post  "/login", to: "login#create"
  delete  "/logout", to: "login#destroy"

  # Normal App routes
  resources :jobs
  resources :users do
    resources :skills
  end

  resources :companies do
    resources :admins
  end

  # API Routes
  namespace :api do
    resources :users, only: [:index, :show]
    resources :jobs, only: [:index, :show]
    resources :companies, only: [:index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :skills, as: :skillable, dependent: :destroy
  has_many :followed_jobs, dependent: :destroy
  has_many :job_interests, through: :followed_jobs, source: :job
  has_many :applied_jobs, -> { where(applied: true) }, class_name: 'FollowedJob'
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  # Validations
  validates :first, :last, :email, :password, presence: true
  validates :first, :last, length: { in: 2..30 }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :password, confirmation: true, length: { in: 6..20 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first, :last, :password_digest, :email)
    end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: register_path, :html => { :multipart => true } ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_login.html.erb
<%= form_tag(login_path, class: "navbar-form navbar-right") do |f| %>
  <div class="form-group">
    <%= text_field_tag :email %>
  </div>
  <div class="form-group">
    <%= text_field_tag :password %>
  </div>
  <div class="form-group">
    <%= submit_tag "Login", class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first %></td>
        <td><%= user.last %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %> | <%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', register_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h4 class=""></h4>
<div class="cards">
  <div class="card">
    <div class="row">
      <div class="col-sm-3">
        <img src="<%=@user.avatar%>" alt="">
      </div>
      <div class="col-sm-9">
        <div class="card-header">
          Info:
        </div>
        <div class="card-copy">
          <p>
            Name: <span class="text-info text-capitalize"><%= @user.first %> <%= @user.last %></span>
          </p>
          <p>
            Email: <span class="text-info text-capitalize"><%= @user.email %> </span>
          </p>
          <p>
            Age: <span class="text-info text-capitalize"><%= @user.email %> </span>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      Summary:
    </div>
    <div class="card-copy">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
    </div>
  </div>
</div>
<hr>
<h2>Skills</h2>
<hr>
<div class="cards">
  <% @user.skills.each do |skill| %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-header">
          Type: <span class="text-info text-capitalize"><%= skill.name %></span>
        </div>
        <div class="card-copy">
          <p>
            Proficiency: <span class="text-info text-capitalize"><%= skill.proficiency %></span>
          </p>
        </div>
      </div>
    </div>
  <% end -%>
</div>